name: booking-order-app
services:
  payment-service:
    container_name: payment-service
    platform: linux/amd64
    image: sikoding20/payment-service:2
    ports:
      - "8003:8003"
    env_file:
      - .env